name: CI/CD pipeline for the Connect Four game
on: [ push, workflow_dispatch]
jobs: 

    build: 
        runs-on: ubuntu-latest

        steps: 
           - name: Setup .NET 7
             uses: actions/setup-dotnet@v3
             with:
                dotnet-version: 7
           - name: Checkout Repo
             uses: actions/checkout@v4
           - name: Cache Dependencies
             uses: actions/cache@v3
             with:
               path: ~/.nuget/packages
               key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
               restore-keys: |
                 ${{ runner.os }}-nuget-
           - name: Build
             run: dotnet build
           - name: Upload Artifacts
             uses: actions/upload-artifact@v3
             with:
               name: build
               path: |
                 ConnectFour*/bin/**
                 ConnectFour*/obj/**
  
    test: 
        runs-on: ubuntu-latest
        needs: build

        steps: 
           - name: Setup .NET 7
             uses: actions/setup-dotnet@v3
             with:
                dotnet-version: 7
           - name: Checkout Repo
             uses: actions/checkout@v4
           - name: Cache Dependencies
             uses: actions/cache@v3
             with:
               path: ~/.nuget/packages
               key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
               restore-keys: |
                 ${{ runner.os }}-nuget-
           - name: Download Artifacts
             uses: actions/download-artifact@v3
             with:
               name: build
           - name: Test
             run: dotnet test --no-restore --no-build

    publish:
        runs-on: ubuntu-latest
        needs: build

        steps: 
           - name: Setup .NET 7
             uses: actions/setup-dotnet@v3
             with:
                dotnet-version: 7
           - name: Checkout Repo
             uses: actions/checkout@v4
           - name: Cache Dependencies
             uses: actions/cache@v3
             with:
               path: ~/.nuget/packages
               key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
               restore-keys: |
                 ${{ runner.os }}-nuget-
           - name: Download Artifacts
             uses: actions/download-artifact@v3
             with:
               name: build
           - name: Publish
             run: dotnet publish --no-restore --no-build ConnectFourWeb
           - name: Upload Artifacts
             uses: actions/upload-artifact@v3
             with:
               name: publish
               path: ConnectFourWeb/bin/Debug/net7.0/publish/**